### ISSUE TITLE
throttled requests seem to have a fixed retry after value independently of the time left to expire

### ISSUE THREAD

**Issue by jogaco** [kickstarter/rack-attack#209] opened 2016-11-21 22:37 UTC
When a request is throttled, the retry-after header value seems to be fixed:the throttle period, independently of the time left for the throttle to expire

**Comment by jeroenvisser101** [comment] 2016-12-12 15:18
Hey, are you using it as described?

```'X-RateLimit-Reset' => (now + (match_data[:period] - now.to_i % match_data[:period])).to_s```

[see here](https://github.com/kickstarter/rack-attack#x-ratelimit-headers-for-well-behaved-clients)

**Comment by jogaco** [comment] 2016-12-12 15:33
Missed that one.
Thanks!

**Comment by jeroenvisser101** [comment] 2016-12-12 15:42
You're welcome :)

**Comment by jogaco** [comment] 2016-12-12 18:12
Hold on.
The default implementation returns this header no matter how much time has passed since the initial throttled request, assuming the maximum requests per hour has been reached:

`Retry-After	3600`

By implementing a custom response, in the direction you pointed out, I agree this can be fixed. But out-of-the-box, the Retry-After response is not correct.

**Comment by jeroenvisser101** [comment] 2016-12-12 22:23
Ah, I didn't know it set this by default. If that's the case, then I would also agree this is a bug

**Comment by grzuy** [comment] 2018-03-22 19:00
Hi @jogaco, thanks for the report :-)

You're right. It sounds like the `Retry-After` is just returning what the throttle period is set to. So yes, it is always returning a fixed value. I also agree that behavior feels a bit counter-intuitive considering what someone might expect out of something named "Retry after".

That said, i am still not decided about what priority to give to this, given it's about giving a better experience to potentially abusive user agents by default.

Might be helpful to understand what your use case is?
Are you also controlling the client that is making the requests to the throttled HTTP endpoint and you want to read `Retry-After` and optimize your wait time?

**Comment by lmansur** [comment] 2018-03-23 00:10
Maybe we allow the header value to be configured? Return nothing at all or return the correct value. We shouldn't be returning the entire period, in my opinion. This harms the abuser (:+1:) but also harms the well-behaved client (:-1:).

**Comment by grzuy** [comment] 2018-03-26 22:19
> Maybe we allow the header value to be configured?

Anyone can already do that by setting a custom `throttled_response`. You mean supporting a different way for configuring that value?

**Comment by lmansur** [comment] 2018-03-27 14:46
Yes, I was thinking of two preset values for `Retry-After`, without having to mess with the `throttled_response`.

It would be configured similar to the cache store, so:

```ruby
Rack::Attack.retry_after = :paranoid # Returns nothing at all. Could be the default
Rack::Attack.retry_after = :realistic   # Returns the "correct" value, as in the time until the next reset
```

The names obviously subject to change, but this is the general idea of it.

**Comment by jogaco** [comment] 2018-03-28 18:03
That would be awesome

**Comment by lmansur** [comment] 2018-03-28 18:06
Building up on the suggestion, `throttled_response` would take precedence. So if I configure `Rack::Attack` to not return anything at all but `throttled_response` implements its own logic, the header would be returned as determined in `throttled_response`

**Comment by grzuy** [comment] 2018-06-20 17:58
@lmansur Yes, I agree something like that would be the best.

I think I'd rather just make it a boolean config value, like `enabled_retry_after_header` or something like that, and make it return the correct value.

Something for `6.0` probably.

**Comment by lmansur** [comment] 2018-06-20 21:39
So just to be clear, the default header value remains the same. If the user wants to return the "realistic" value, he will use something in the likes of `Rack::Attack.enabled_retry_after_header = true` in the initializer. If the user doesn't want to set this globally or wants to override our logic, he can implement his own within the `throttled_response`.

Unless someone wants to tackle this (maybe a first time contributor? :tada:), I can work on it around July.

**Comment by grzuy** [comment] 2018-06-21 14:21
> @grzuy So just to be clear, the default header value remains the same.

I was thinking more that it doesn't remain the same. That we re-implmenet the `Retry-After` header to return "realistic" or nothing based on that new configuration value. Because of that it would be a breaking change, which means it's a target for `6.0` release.

> If the user wants to return the "realistic" value, he will use something in the likes of Rack::Attack.enabled_retry_after_header = true in the initializer.

Yes

> If the user doesn't want to set this globally or wants to override our logic, he can implement his own within the throttled_response.

Yes

> Unless someone wants to tackle this (maybe a first time contributor? tada), I can work on it around July.

Cool :+1:

**Comment by grzuy** [comment] 2018-06-21 17:31
> Got it! So by default, we return nothing?

Yes.

I think it sounds like a good fit for an opt-in feature, instead of opt-out.

**Comment by lmansur** [comment] 2018-06-22 23:19
Got it. 
So, we need to:

**Allow the configuration of the `Retry-After` header.** The interface would be:
```ruby
Rack::Attack.enabled_retry_after_header = true
```

The name of the attribute is subject to change. By default, its value is `false`. The other possible value is `true`.

When the attribute is `false`, the `Retry-After` header returns **nothing**. This is the default state.
When the attribute is `true`,  the `Retry-After` header returns the time, in seconds, until the counter resets. In other words, this is how many seconds the user has to wait until they can start sending requests again.

The `Retry-After` header should still be overwritable by the `throttled_response` attribute, regardless of the configuration.

We should also update the README with this new interface.

I can't commit to implement this yet, so if anyone wants to tackle it, go for it!

**Comment by grzuy** [comment] 2018-06-29 13:28
Agree.
Thanks for writing down the spec.

**Comment by imi56** [comment] 2018-08-27 10:45
It's been around 2 years for this issue. But the issue is still pending. Please share the progress on this.

**Comment by lmansur** [comment] 2018-08-27 13:54
@imi56 as far as I know there is no progress on the change yet. The changes have been discussed and agreed upon, so all there's left is for someone to implement it.

**Comment by imi56** [comment] 2018-08-28 05:13
@lmansur I found my issue duplicate of this issue so I closed mine. However, the issue remains the same means no solution found yet.

**Comment by lmansur** [comment] 2018-08-30 00:40
@imi56 the link I posted in your issue was wrong, I fixed it now.

The issues are similar, but not the same. You can provide how much time the client has to wait in the throttle response, as explained [here](https://github.com/kickstarter/rack-attack#ratelimit-headers-for-well-behaved-clients).

However, if that isn't enough for you, we need to wait until this issue gets solved.

**Comment by lmansur** [comment] 2018-12-14 12:39
@imi56 the `epoch_time` key was added in [`v5.4.0`](https://github.com/kickstarter/rack-attack/blob/master/CHANGELOG.md#540---2018-07-02). If you can't upgrade the gem yet, you can use `Time.now` instead of `match_data[:epoch_time]`. However, you will be susceptible to race conditions, as explained in #283

**Closed** 2019-10-16 22:41 UTC
Labels: area: throttle, type: feature request
