### ISSUE TITLE
Why so many memcached requests? (26 per every request)

### ISSUE THREAD

**Issue by feliperaul** [kickstarter/rack-attack#414] opened 2019-05-11 19:41 UTC
I'm using the solution posted on #210 (Throttle + Fail2Ban), and while debugging performance using `memcached -vv`,  I was surprised by the number of memcached requests.

Here's my rack_attack.rb file:

```
Rack::Attack.throttle('orders/new', limit: 10, period: 1.minute) do |request|
  
  if request.path.include?('/orders/new'.freeze)
    request.ip
  end
end

Rack::Attack.blocklist('orders-new-ban-from-site') do |request|

  Rack::Attack::Fail2Ban.filter("ban-throttle-orders/new-#{request.ip}", maxretry: 0, findtime: 1.minute, bantime: 1.day) do
    
    count = Rails.cache.read("rack::attack:#{Time.now.to_i/1.minute}:'orders/new'}:#{request.ip}")

    count && count.to_i > 10

  end

end

```

With that config, here's the amount of memcached traffic received on **every single request** (it's a common request that DOES NOT even match the /orders/new path):

> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 
> <19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
> 
> <19 GET rack::attack:25960057:orders/new:127.0.0.1
> 

I tried to understand what's going on, but couldn't figure out how many memcached queries for just one single request. 

That's 26 fail2ban requests and 26 checks for the throttle ,totalling a staggering 52 memcached queries for every single rails request. 

Here's the full memcached log for each one of these requests (they loop):

```
<19 GET rack::attack:25960057:orders/new:127.0.0.1
>19 Writing an error: Not found
>19 Writing bin response:
>19   0x81 0x00 0x00 0x00
>19   0x00 0x00 0x00 0x01
>19   0x00 0x00 0x00 0x09
>19   0x00 0x00 0x00 0x00
>19   0x00 0x00 0x00 0x00
>19   0x00 0x00 0x00 0x00
<19 Read binary protocol data:
<19    0x80 0x00 0x00 0x3b
<19    0x00 0x00 0x00 0x00
<19    0x00 0x00 0x00 0x3b
<19    0x00 0x00 0x00 0x00
<19    0x00 0x00 0x00 0x00
<19    0x00 0x00 0x00 0x00
<19 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
>19 Writing an error: Not found
>19 Writing bin response:
>19   0x81 0x00 0x00 0x00
>19   0x00 0x00 0x00 0x01
>19   0x00 0x00 0x00 0x09
>19   0x00 0x00 0x00 0x00
>19   0x00 0x00 0x00 0x00
>19   0x00 0x00 0x00 0x00
<19 Read binary protocol data:
<19    0x80 0x00 0x00 0x2a
<19    0x00 0x00 0x00 0x00
<19    0x00 0x00 0x00 0x2a
<19    0x00 0x00 0x00 0x00
<19    0x00 0x00 0x00 0x00
<19    0x00 0x00 0x00 0x00
```

**Comment by lmansur** [comment] 2019-05-18 01:02
That's very odd.

Are you able to reproduce this bug in a small test app and share it with us?

**Comment by grzuy** [comment] 2019-10-23 17:43
Hi @feliperaul ,

I can't reproduce the problem in the following small test app https://github.com/grzuy/test_app_rack_attack_414, which is a new rails app with just rack-attack, dalli and your rack-attack config.

Feel free to try reproduce the issue by forking that app and adding more stuff.

Thank you!

**Comment by grzuy** [comment] 2019-10-23 17:45
FTR, this is all the output I get for 1 request:

```
<27 new auto-negotiating client connection
27: Client using the binary protocol
<27 Read binary protocol data:
<27    0x80 0x0b 0x00 0x00
<27    0x00 0x00 0x00 0x00
<27    0x00 0x00 0x00 0x00
<27    0x00 0x00 0x00 0x00
<27    0x00 0x00 0x00 0x00
<27    0x00 0x00 0x00 0x00
>27 Writing bin response:
>27   0x81 0x0b 0x00 0x00
>27   0x00 0x00 0x00 0x00
>27   0x00 0x00 0x00 0x06
>27   0x00 0x00 0x00 0x00
>27   0x00 0x00 0x00 0x00
>27   0x00 0x00 0x00 0x00
<27 Read binary protocol data:
<27    0x80 0x00 0x00 0x3b
<27    0x00 0x00 0x00 0x00
<27    0x00 0x00 0x00 0x3b
<27    0x00 0x00 0x00 0x00
<27    0x00 0x00 0x00 0x00
<27    0x00 0x00 0x00 0x00
<27 GET rack::attack:fail2ban:ban:ban-throttle-orders/new-127.0.0.1
>27 Writing an error: Not found
>27 Writing bin response:
>27   0x81 0x00 0x00 0x00
>27   0x00 0x00 0x00 0x01
>27   0x00 0x00 0x00 0x09
>27   0x00 0x00 0x00 0x00
>27   0x00 0x00 0x00 0x00
>27   0x00 0x00 0x00 0x00
<27 Read binary protocol data:
<27    0x80 0x00 0x00 0x2d
<27    0x00 0x00 0x00 0x00
<27    0x00 0x00 0x00 0x2d
<27    0x00 0x00 0x00 0x00
<27    0x00 0x00 0x00 0x00
<27    0x00 0x00 0x00 0x00
<27 GET rack::attack:26197544:'orders/new'}:127.0.0.1
>27 Writing an error: Not found
>27 Writing bin response:
>27   0x81 0x00 0x00 0x00
>27   0x00 0x00 0x00 0x01
>27   0x00 0x00 0x00 0x09
>27   0x00 0x00 0x00 0x00
>27   0x00 0x00 0x00 0x00
>27   0x00 0x00 0x00 0x00
```

**Comment by feliperaul** [comment] 2019-10-23 17:49
Thank you, will try to do so as soon as I have some spare time! Thanks for
the effort.

Em qua, 23 de out de 2019 às 14:43, Gonzalo Rodriguez <
notifications@github.com> escreveu:

**Comment by grzuy** [comment] 2019-12-17 21:19
Closing for now until we have a way to reproduce and verify the issue.

**Closed by grzuy** 2019-12-17 21:19 UTC
Labels: area: fail2ban, status: can't reproduce, type: question
