### ISSUE TITLE
Sometimes throttle resets unexpectedly

### ISSUE THREAD

**Issue by Aldekein** [kickstarter/rack-attack#125] opened 2015-04-22 14:00 UTC
Hello,

I'm trying to implement two throttles:

```
throttle('logins/ip', :limit => 5, :period => 20.seconds) do |req|
    if req.path.starts_with?('/sessions') && req.post?
      req.cf_ip
    end
  end

 throttle('logins/email', :limit => 5, :period => 20.seconds) do |req|
    if req.path.starts_with?('/sessions') && req.post?
      # return the email if present, nil otherwise
      req.params['login'].presence
    end
  end
```

I am testing it with running a JS script in Chrome console which does 15 attempts. Most of time it's working correctly, first 5 attempts are successful, other ones are 429 errors. But sometimes i get strange results:

```
Invalid login or password.
Wed Apr 22 2015 21:38:40 GMT+0800 (WITA)

Invalid login or password.
Wed Apr 22 2015 21:38:41 GMT+0800 (WITA)

Invalid login or password.
Wed Apr 22 2015 21:38:41 GMT+0800 (WITA)

Invalid login or password.
Wed Apr 22 2015 21:38:42 GMT+0800 (WITA)

Invalid login or password.
Wed Apr 22 2015 21:38:42 GMT+0800 (WITA)

vendor-fd9f68ee.js:32 POST http://sandbox.srv:25005/sessions.json 429 (OK)e @ vendor-fd9f68ee.js:32w @ vendor-fd9f68ee.js:32$get.l @ vendor-fd9f68ee.js:32u @ vendor-fd9f68ee.js:32(anonymous function) @ vendor-fd9f68ee.js:32$get.d.$eval @ vendor-fd9f68ee.js:33$get.d.$digest @ vendor-fd9f68ee.js:32$get.d.$apply @ vendor-fd9f68ee.js:33(anonymous function) @ vendor-fd9f68ee.js:34Q.event.dispatch @ vendor-fd9f68ee.js:25Q.event.add.v.handle @ vendor-fd9f68ee.js:24loginRepeater @ VM167:2(anonymous function) @ VM167:2
Oops, something went wrong. Please try again later
Wed Apr 22 2015 21:38:43 GMT+0800 (WITA)

vendor-fd9f68ee.js:32 POST http://sandbox.srv:25005/sessions.json 429 (OK)e @ vendor-fd9f68ee.js:32w @ vendor-fd9f68ee.js:32$get.l @ vendor-fd9f68ee.js:32u @ vendor-fd9f68ee.js:32(anonymous function) @ vendor-fd9f68ee.js:32$get.d.$eval @ vendor-fd9f68ee.js:33$get.d.$digest @ vendor-fd9f68ee.js:32$get.d.$apply @ vendor-fd9f68ee.js:33(anonymous function) @ vendor-fd9f68ee.js:34Q.event.dispatch @ vendor-fd9f68ee.js:25Q.event.add.v.handle @ vendor-fd9f68ee.js:24loginRepeater @ VM167:2(anonymous function) @ VM167:2
Oops, something went wrong. Please try again later
Wed Apr 22 2015 21:38:43 GMT+0800 (WITA)

Invalid login or password.
Wed Apr 22 2015 21:38:44 GMT+0800 (WITA)

Invalid login or password.
Wed Apr 22 2015 21:38:44 GMT+0800 (WITA)

Invalid login or password.
Wed Apr 22 2015 21:38:45 GMT+0800 (WITA)

Invalid login or password.
Wed Apr 22 2015 21:38:45 GMT+0800 (WITA)

Invalid login or password.
Wed Apr 22 2015 21:38:46 GMT+0800 (WITA)

vendor-fd9f68ee.js:32 POST http://sandbox.srv:25005/sessions.json 429 (OK)e @ vendor-fd9f68ee.js:32w @ vendor-fd9f68ee.js:32$get.l @ vendor-fd9f68ee.js:32u @ vendor-fd9f68ee.js:32(anonymous function) @ vendor-fd9f68ee.js:32$get.d.$eval @ vendor-fd9f68ee.js:33$get.d.$digest @ vendor-fd9f68ee.js:32$get.d.$apply @ vendor-fd9f68ee.js:33(anonymous function) @ vendor-fd9f68ee.js:34Q.event.dispatch @ vendor-fd9f68ee.js:25Q.event.add.v.handle @ vendor-fd9f68ee.js:24loginRepeater @ VM167:2(anonymous function) @ VM167:2
Oops, something went wrong. Please try again later
Wed Apr 22 2015 21:38:46 GMT+0800 (WITA)

vendor-fd9f68ee.js:32 POST http://sandbox.srv:25005/sessions.json 429 (OK)e @ vendor-fd9f68ee.js:32w @ vendor-fd9f68ee.js:32$get.l @ vendor-fd9f68ee.js:32u @ vendor-fd9f68ee.js:32(anonymous function) @ vendor-fd9f68ee.js:32$get.d.$eval @ vendor-fd9f68ee.js:33$get.d.$digest @ vendor-fd9f68ee.js:32$get.d.$apply @ vendor-fd9f68ee.js:33(anonymous function) @ vendor-fd9f68ee.js:34Q.event.dispatch @ vendor-fd9f68ee.js:25Q.event.add.v.handle @ vendor-fd9f68ee.js:24loginRepeater @ VM167:2(anonymous function) @ VM167:2
Oops, something went wrong. Please try again later
Wed Apr 22 2015 21:38:47 GMT+0800 (WITA)

vendor-fd9f68ee.js:32 POST http://sandbox.srv:25005/sessions.json 429 (OK)e @ vendor-fd9f68ee.js:32w @ vendor-fd9f68ee.js:32$get.l @ vendor-fd9f68ee.js:32u @ vendor-fd9f68ee.js:32(anonymous function) @ vendor-fd9f68ee.js:32$get.d.$eval @ vendor-fd9f68ee.js:33$get.d.$digest @ vendor-fd9f68ee.js:32$get.d.$apply @ vendor-fd9f68ee.js:33(anonymous function) @ vendor-fd9f68ee.js:34Q.event.dispatch @ vendor-fd9f68ee.js:25Q.event.add.v.handle @ vendor-fd9f68ee.js:24loginRepeater @ VM167:2(anonymous function) @ VM167:2
Oops, something went wrong. Please try again later
```

Here, 5 attempts go through, then throttling turns on, blocks 2 requests, then suddenly it turns off and allows five more requests before blocking again. I am not sure what's the reason and where I should start debug. Any ideas?

**Comment by zmillman** [comment] 2015-04-22 17:42
Hmm, I'm not sure what's breaking :cry: 

A couple things I'd try:
* Is it something caused by having two throttles? If you disable one of them, does it work as expected?
* Is the expiration period reached while you're running the test? If you set the period to e.g. 5 minutes, does it still get strangely reset?

**Comment by Aldekein** [comment] 2015-04-24 17:14
Yes, when I disabled one - it worked correctly (or at least this problem did not reproduce while I tried). Here is one more weird case (when both enabled):

```
Invalid login or password.
Sat Apr 25 2015 01:08:57 GMT+0800 (WITA)

Invalid login or password.
Sat Apr 25 2015 01:08:58 GMT+0800 (WITA)

Invalid login or password.
Sat Apr 25 2015 01:08:59 GMT+0800 (WITA)

Invalid login or password.
Sat Apr 25 2015 01:08:59 GMT+0800 (WITA)

Invalid login or password.
Sat Apr 25 2015 01:09:00 GMT+0800 (WITA)

Invalid login or password.
Sat Apr 25 2015 01:09:01 GMT+0800 (WITA)

Invalid login or password.
Sat Apr 25 2015 01:09:02 GMT+0800 (WITA)

Invalid login or password.
Sat Apr 25 2015 01:09:02 GMT+0800 (WITA)

Invalid login or password.
Sat Apr 25 2015 01:09:03 GMT+0800 (WITA)

vendor-21e4401a.js:32 POST http://127.0.0.1:3000/sessions.json 429 (OK)(anonymous function) @ vendor-21e4401a.js:32w @ vendor-21e4401a.js:32l @ vendor-21e4401a.js:32u @ vendor-21e4401a.js:32(anonymous function) @ vendor-21e4401a.js:32d.$eval @ vendor-21e4401a.js:33d.$digest @ vendor-21e4401a.js:32d.$apply @ vendor-21e4401a.js:33(anonymous function) @ vendor-21e4401a.js:34Q.event.dispatch @ vendor-21e4401a.js:25v.handle @ vendor-21e4401a.js:24loginRepeater @ VM710:2(anonymous function) @ VM710:2
Something went wrong. Please try again later.
Sat Apr 25 2015 01:09:03 GMT+0800 (WITA)

vendor-21e4401a.js:32 POST http://127.0.0.1:3000/sessions.json 429 (OK)(anonymous function) @ vendor-21e4401a.js:32w @ vendor-21e4401a.js:32l @ vendor-21e4401a.js:32u @ vendor-21e4401a.js:32(anonymous function) @ vendor-21e4401a.js:32d.$eval @ vendor-21e4401a.js:33d.$digest @ vendor-21e4401a.js:32d.$apply @ vendor-21e4401a.js:33(anonymous function) @ vendor-21e4401a.js:34Q.event.dispatch @ vendor-21e4401a.js:25v.handle @ vendor-21e4401a.js:24loginRepeater @ VM710:2(anonymous function) @ VM710:2
Something went wrong. Please try again later.
Sat Apr 25 2015 01:09:04 GMT+0800 (WITA)

.... more blocked requests ....
```

As you can see there were 9 passed requests instead of 5 possible in a row!
I've made a dump of Rack::Attack.cache.store keys (ActiveSupport::Cache::MemoryStore) right after this:

```
Array (17 element(s))
"rack::attack:4766317:req/ip:127.0.0.1"
"rack::attack:71494757:logins/ip:127.0.0.1"
"rack::attack:71494757:logins/email:aldekein+test2@myevil.info"
"rack::attack:71494758:logins/ip:127.0.0.1"
"rack::attack:71494758:logins/email:aldekein+test2@myevil.info"
"rack::attack:71494761:logins/ip:127.0.0.1"
"rack::attack:71494761:logins/email:aldekein+test2@myevil.info"
"rack::attack:71494762:logins/ip:127.0.0.1"
"rack::attack:71494762:logins/email:aldekein+test2@myevil.info"
"rack::attack:71494763:logins/ip:127.0.0.1"
"rack::attack:71494763:logins/email:aldekein+test2@myevil.info"
"rack::attack:71494764:logins/ip:127.0.0.1"
"rack::attack:71494764:logins/email:aldekein+test2@myevil.info"
"rack::attack:71494766:logins/ip:127.0.0.1"
"rack::attack:71494766:logins/email:aldekein+test2@myevil.info"
"rack::attack:71494767:logins/ip:127.0.0.1"
"rack::attack:71494767:logins/email:aldekein+test2@myevil.info"
```

**Comment by ktheory** [comment] 2015-04-24 19:27
> As you can see there were 9 passed requests instead of 5 possible in a row!

This is actually working as intended. :smile: 4 of the requests happened between `01:08:40..01:08:59`, at which point the throttle was reset (b/c the key changed). Then 5 requests were allowed from `01:09:00..01:09:19`.

As for your original post, I'm not sure what's going on. But it's unusual to use `ActiveSupport::Cache::MemoryStore` as the Rack::Attack cache. It would definitely not work as expected if you have more than one server process.

Can you try using Dalli (memcache) or RedisStore and see if you can recreate the problem?

**Comment by Aldekein** [comment] 2015-04-25 13:29
I've used a class that extends MemoryStore for debug purpose (it's mentioned here - https://github.com/kickstarter/rack-attack/wiki/Example-Configuration). Generally, I did not set Rack::Attack.cache.store at all. Is default value ok or should I set RedisStore?

**Comment by ktheory** [comment] 2015-06-28 00:48
MemoryStore is not recommended for production because state is not shared between processes. RedisStore or Dalli (memcache) use a shared remote resource; that's why they're recommended.

Gonna close this out since it looks like rack-attack is working as intended.

**Closed by ktheory** 2015-06-28 00:48 UTC
